# Imagem do node 22 oficial
FROM node:22

WORKDIR /app

# Configurar o ambiente Node.js
ENV NODE_ENV=development
ENV PORT=3000

COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src
COPY prisma ./prisma

RUN npm install
RUN npm install -D tsconfig-paths ts-node-dev
RUN npx prisma generate

# Expor a porta 3000
EXPOSE 3000

ENTRYPOINT ["npm", "run", "dev"]